// Generated by https://quicktype.io

export interface JSONApiResponse<JSONApiData> {
    data: JSONApiData;
}

export type JSONApiResourceResponse<Attributes = any, Relationships = any> = JSONApiResponse<
    JSONApiResource<Attributes, Relationships>
>

export type JSONApiResourceListingResponse = JSONApiResponse<JSONApiResource[]>

export interface JSONApiResource<Attributes = any, Relationships = any> {
    type: string;
    id: string;
    attributes: Attributes;
    relationships: Relationships;
}
