/* tslint:disable */
/* eslint-disable */
// This file was automatically generated and should not be edited.

//==============================================================
// START Enums and Input Objects
//==============================================================

export interface CampaignContributionSupplyInput {
  campaignSupplyId: string;
  quantity: number;
}

/**
 * Autogenerated input type of CreateCampaignContribution
 */
export interface CreateCampaignContributionInput {
  userId: string;
  campaignId: string;
  contributionSupplies: CampaignContributionSupplyInput[];
  clientMutationId?: string | null;
}

//==============================================================
// END Enums and Input Objects
//==============================================================
